sudo: required
services:
- docker
language: java
dist: bionic
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=petreskiv/code-exercises:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
#  - secure: RNxWF1EbL8dqBxXeB7Cm2Q586bKQ1aGrrJHvKYVpjZqYueZDBd5cm4JEOZ+J9IZUx9Dh5v4TXvezqnjX9KsCFGPYM/CqdGCt0QRcupRC33K+9kMZXfzi8QYtdMqqaQwNGj6nuqCtg7sVmZdQ8ZcXeEHaENb27tECQyBueyD2pyDfR7JXMZ8rFAvJFExb/hNYcyINRuqH3I16Bw4qyLhzwONNWpk/krl08rwM9aha6Ts6TFYBI+QGUAT4qu2ekHDgxxD4AoiZKvCGTUO6j9kVVxe/GjDIJkJX1QInAOrZTYLPND2PMLyJTYBHhJNvD7GNIsX7qcGXOBrLSBw5vPccbheWFDnexViuAm6neA9cWw8B4IqfZDY3SUtKPIwKHYuMy73FSSh9hLJWdS+GsdpVVMdRsh4l90FK3uLhrdIwhtAJYz6CfN11JN56r0wD9qRfASvR5Kd5o/EEYQf2qYoN57M4deBfWF4ZGH4pv7u4EkyMjowNlJ4bZxfOkCzKGoMeVaA7Ivyr3PObqIm1pBEV1vNS8tm2cOLC6m9JjWAQhYts55iajHbmpV1YlglvwZtnyLwQEixyixlGWqAgonQWQYefCfBmIpIC+nqjtMWT1TPz4Xz5E5Dlax59rzECGb1Rcn/IOkllcVYPOZAKk9ZqzwmPydYN5x4PrFnlqYKTG+w=
#  - secure: uQc5bkXrx5xgOMXU8VCo1GK+sg4QB6aoRGC7h6Xuv0Kk86NEuVmPJy/WlvyJeOEWy0C0tXRa/qD9COyzQ5nXO2k1bEXcZhw8NpK7nZTp5+ArcmR2wLdoFsdqindljhASuA3K4/YEfGMwWyL7vWPzKaUKszJi4MNBqaXuaL78T3Et6vMn3vnV6y+CifbOwIBlJSTlsn3xBaWivZIcYMm5CL49z3lrpLld4E1KBtOkqjnnQDAemViE+BfStQa5XgkUFTRwZX3FKhnPgDw5FwD68F2k3+Ff85yHyHPuNXPT27eea6KA7QUofQ67jjmVCYs47dHjcUtHMaDwZvYsifEXNwvTw7A3kP4YlJE1jwQIOYdhGGlrC6RNkJ9fsggqkeVrH5UwDMa5cV4YK/2OjqSvjI1RKT31Cx40M8RLPh72HA1GcSiulFc/xqY/5AM5Ip/VkYZGJ92m0UdfyBMUNjzU3izQRzXTA/x+EqX+5wKG0GvyzamHfoacwQgkgQUQqU40fDSE31wnGOIpYC2cjXVs/EpSEKuAXhbrFhlU0xpfavGGeS2Mxj2Ue0WidvANXOIkM+6t+9YDVCCvrZAbdftY9MPAE1Gbwhnu+w4Le1c8E62wkk0SyeFcetCOfPh9RpiHxqHIWjJuUYR8B73kxiPV67aVNaqov7bEPgYYlcQgSBc=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
#after_success:
#- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#- docker push "$DOCKER_IMAGE"
