version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=exercise-metadata
    ports:
      - "5432:5432"
  exercises:
    image: petreskiv/code-exercises:1.0.0-SNAPSHOT-6.1
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/exercise-metadata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=dbuser
    ports:
      - "8080:8080"
    depends_on:
      - postgres