kumuluzee:
  name: code-exercises
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ImageMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/exercise-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ImageMetadataDS
      etcd-health-check:
        connection-url: http://etcd:2379/health
  metrics:
    web-instrumentation:
      - name: exercises-endpoint
        url-pattern: /v1/exercises/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                         <Configuration name="exercises">
                             <Appenders>
                                 <Console name="console" target="SYSTEM_OUT">
                                     <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                 </Console>
                                 <Socket name="logstash" host="7d264c39-0e8a-4a2b-b850-db059d5fdb1b-ls.logit.io"
                                 port="11963" protocol="tcp">
                                     <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                 </Socket>
                             </Appenders>
                             <Loggers>
                                 <!-- Default logger -->
                                 <Root level="all">
                                     <AppenderRef ref="console" level="info"/>
                                     <AppenderRef ref="logstash" level="trace"/>
                                 </Root>
                             </Loggers>
                         </Configuration>'
  streaming:
    kafka:
      producer:
        bootstrap-servers: moped-01.srvs.cloudkafka.com:9094
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        group-id: code
        sasl-jaas-config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="4nqq16cf" password="v4QobppxNg_Xe1Dhx4NrDTHlN5cfkxZZ";'
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        session-timeout-ms: 30000
configuration-properties:
  code-inputs:
    enabled: true
  code-outputs:
    enabled: true